services:
  berufsschule:
    image: nginx
    container_name: berufsschule
    volumes:
      - ./html:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.berufsschule.entrypoints: https
      traefik.http.routers.berufsschule.rule: Host(`berufsschule.patrikvonmalottki.de`) && PathPrefix(`/`)
      traefik.http.routers.berufsschule.tls: true
      traefik.http.routers.berufsschule.service: berufsschule
      traefik.http.services.berufsschule.loadbalancer.server.port: 80
      traefik.docker.network: proxy
    networks:
      - proxy

networks:
  proxy:
    external: true
