insert into cmn_application_config (
    config_key_code,
    config_key_name,
    config_value,
    description,
    environment,
    module,
    active_flag
) values (
    'APP_NAME',
    'App Name',
    'Lern',
    'Name of the application.',
    'GLOBAL',
    'GLOBAL',
    'Y'
), (
    'APP_ENVIRONMENT_NAME',
    'App Environment Name',
    'LERN_APPLICATION',
    'Name of the Lern app environment.',
    'APP',
    'APP',
    'Y'
), (
    'APP_VERSION',
    'App Version',
    '1.0',
    'Current version of the application.',
    'GLOBAL',
    'GLOBAL',
    'Y'
), (
    'LOG_LEVEL_TRACE',
    'Log Level Trace',
    '1',
    'Trace Log level value of the application.',
    'GLOBAL',
    'GLOBAL',
    'Y'
), (
    'LOG_LEVEL_INFO',
    'Log Level Info',
    '2',
    'Info Log level value of the application.',
    'GLOBAL',
    'GLOBAL',
    'Y'
), (
    'LOG_LEVEL_WARNING',
    'Log Level Warning',
    '3',
    'Warning Log level value of the application.',
    'GLOBAL',
    'GLOBAL',
    'Y'
), (
    'LOG_LEVEL_ERROR',
    'Log Level Error',
    '4',
    'Error Log level value of the application.',
    'GLOBAL',
    'GLOBAL',
    'Y'
), (
    'LOG_LEVEL_CRITICAL',
    'Log Level Critical',
    '5',
    'Critical Log level value of the application.',
    'GLOBAL',
    'GLOBAL',
    'Y'
), (
    'DEFAULT_LOG_LEVEL',
    'Default Log Level',
    '2',
    'Log level of the application.',
    'GLOBAL',
    'GLOBAL',
    'Y'
) (
    'ACCESS_TOKEN_DURATION',
    'Access Token Duration',
    '5',
    'Duration of the access token (in minutes) generated by the backend.',
    'FRONTEND',
    'GLOBAL',
    'Y'
) (
    'REFRESH_TOKEN_DURATION',
    'Refresh Token Duration',
    '30',
    'Duration of the refresh token (in minutes) generated by the backend.',
    'FRONTEND',
    'GLOBAL',
    'Y'
);